app:
  datasource:
    jdbc-url: jdbc:postgresql://34.159.61.208/postgres
    username: postgres
    password: "@deathgun233"
    pool-size: 30
    minimumIdle: 2
    idleTimeout: 10000
    connectionTimeout: 10000
    leakDetectionThreshold: 300000
    max-lifetime: 200000