app:
  datasource:
    jdbc-url: jdbc:postgresql://20.56.120.77:5432/surfinbirddb
    username: postgres
    password: deathgun233
    pool-size: 30
    minimumIdle: 2
    idleTimeout: 300000
    connectionTimeout: 300000
    leakDetectionThreshold: 300000